version: '3.8'

services:
  postgres:
    image: postgres:16

    container_name: postgres
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: 88888888
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk
    container_name: task_management_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run

volumes:
  postgres_data: